module SearchesHelper

  class SearchResults

    attr_accessor :spot_types_by_number
    attr_accessor :spots

    @@spot_types = [
      "accounting",
      "airport",
      "amusement_park",
      "aquarium",
      "art_gallery",
      "atm",
      "bakery",
      "bank",
      "bar",
      "beauty_salon",
      "bicycle_store",
      "book_store",
      "bowling_alley",
      "bus_station",
      "cafe",
      "campground",
      "car_dealer",
      "car_rental",
      "car_repair",
      "car_wash",
      "casino",
      "cemetery",
      "church",
      "city_hall",
      "clothing_store",
      "convenience_store",
      "courthouse",
      "dentist",
      "department_store",
      "doctor",
      "electrician",
      "electronics_store",
      "embassy",
      "establishment",
      "finance",
      "fire_station",
      "florist",
      "food",
      "funeral_home",
      "furniture_store",
      "gas_station",
      "general_contractor",
      "grocery_or_supermarket",
      "gym",
      "hair_care",
      "hardware_store",
      "health",
      "hindu_temple",
      "home_goods_store",
      "hospital",
      "insurance_agency",
      "jewelry_store",
      "laundry",
      "lawyer",
      "library",
      "liquor_store",
      "local_government_office",
      "locksmith",
      "lodging",
      "meal_delivery",
      "meal_takeaway",
      "mosque",
      "movie_rental",
      "movie_theater",
      "moving_company",
      "museum",
      "night_club",
      "painter",
      "park",
      "parking",
      "pet_store",
      "pharmacy",
      "physiotherapist",
      "place_of_worship",
      "plumber",
      "police",
      "post_office",
      "real_estate_agency",
      "restaurant",
      "roofing_contractor",
      "rv_park",
      "school",
      "shoe_store",
      "shopping_mall",
      "spa",
      "stadium",
      "storage",
      "store",
      "subway_station",
      "synagogue",
      "taxi_stand",
      "train_station",
      "transit_station",
      "travel_agency",
      "university",
      "veterinary_care",
      "zoo"
    ]

    @@spot_excluded_types = [
      "accounting",
      "airport",
      "atm",
      "bank",
      "bus_station",
      "car_dealer",
      "car_rental",
      "car_repair",
      "car_wash",
      "dentist",
      "doctor",
      "electrician",
      "embassy",
      "finance",
      "fire_station",
      "funeral_home",
      "furniture_store",
      "gas_station",
      "hospital",
      "insurance_agency",
      "laundry",
      "lawyer",
      "local_government_office",
      "moving_company",
      "parking",
      "pharmacy",
      "physiotherapist",
      "police",
      "post_office",
      "subway_station",
      "taxi_stand",
      "train_station",
      "travel_agency",
      "veterinary_care"
    ]

    def initialize(latitude, longitude)
      @client = GooglePlaces::Client.new("AIzaSyBHJpb9fD5eBeN-wd0Xq0vYkTUtRSEgr0U")
      # @spots = @client.spots(latitude, longitude, radius: 5000)
      @spots = @client.spots(40.7711329, -73.9741874, radius: 2000)

      @spot_types_by_number = {}
      @spot_types_by_number.default = 0
      @spots.each do |spot|
        spot.types.each do |type|
          @spot_types_by_number[type] += 1
        end
      end
    end

  end
end
